source 'https://rubygems.org'

ruby '2.3.4'
gem 'mysql2', '~> 0.3.18'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 5.0.0', '< 5.1'
gem 'active_model_serializers'
gem 'dijkstra', github: "oscartanner/dijkstra.gem"
gem 'redis-rails'

group :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'forgery'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'faker'
end

group :test, :development do
  gem 'byebug'
end
